### PR TITLE
Self configuring CLI

### PR DESCRIPTION
**Pull request by domwong**
Discussion/spec for self configuring CLI

### CODE REVIEW

**Comment by asim** [comment]
To add an alternative design to this would be to approach it from how the api, proxy and web components operate right now. Discovery is dynamic and done on the fly based on the registry. The registry contains endpoints and services and based on historic design of micro is the single source for any service we talk to and it feels as though the CLI should be no different.

e.g a cache service with endpoint Cache.Get/Put/Del 

proto interface
```
service Cache {
  rpc Get(GetRequest) returns (GetResponse) {};
  ...
}

message PutRequest {
  string key = 1;
  string value = 2;
}

message GetRequest {
  string key = 1;
}

message GetResponse {
  string key = 1;
  string value = 2;
}
```

```
micro cache put --key foo --value bar
micro cache get --key get
```

Input fields are automatically mapped from flags in the context in the CLI

The reason to take this approach is because services then become emergent in all clients {api, web, cli, bot, proxy} rather than having to explicitly define the behaviour for each. They also automatically appear as they appear on the platform rather than having to refresh a cache using `micro init`.

**Comment by domwong** [comment]
I like that as the evolution of `micro call` but you do have the issue of potential name clashes if the service names are not namespaced. e.g. If I have a service called `new` what happens if I do `micro new` does it hit the new service or does it cut me some boilerplate new service? 

Which services appear in this list? All of them? That could be a lot of services. Would also need to think about what `micro help` looks like in this scenario? There's no concept of help description which could make developer UX pretty poor.

I feel like there's a missing piece of abstraction/encapsulation here which could make this very verbose/complex in the base case whereas we would like to keep dev ux at top of mind

**Comment by asim** [comment]
I agree on your point about clashes, so I propose a couple things here. 1 built ins like "new" always take precedence, so theres scenarios where we just can't have certain service names. 2. You're right, we should continue to scope services to `micro services` rather than it being explicitly in `micro --help`.  We can maintain `micro --help` for this explicit thing you're talking about.

In this case I'd say we need to strike a balance and know how to expose specific commands we care about in that --help list perhaps by calling the micro server since you probably want this kind of functionality to be baked in if `micro init` is a built in command.

**Comment by domwong** [comment]
Scoping to just the micro platform services is a good solution to keep the list trim. 

If doing `micro init` pulls down the help text too, I wonder if we can auto generate some help text from proto comments or something. 

Thinking this through with an example then. How do we make micro login work? We create a new `go.micro.login` service that lives as a core service. We have a version for OSS that lives in github.com/micro/micro ? And then the m3o one lives in github.com/micro/services?

**Comment by asim** [comment]
I read back the full doc and agree with the approach for CLI commands. I think if the server has an endpoint and we can query that for updates then we end up in a pretty solid position. If that endpoint returns a list of binaries that can be downloaded and we store with the `micro-` prefix then it makes a whole lot of sense, potentially even for additional core services you may want to add to a running system. 

Right now `micro init` has behaved as a thing which polls https://micro.mu/update to look for docker image changes and then reboots. This feels like a good logical evolution of that to configure micro in totality.

Separately I think the `micro call` moving to the thing we've discussed additionally makes sense. 

Lets figure out where this endpoint would live. Ideally in the server so we can do Server.Update or something

**Comment by domwong** [comment]
> What do you think?

Depends on the use case. 

If the semantics of the thing are the same but the implementation is different on local vs m3o then we should strive to maintain the same API but swap out the implementation of the service so the CLI makes the same call. If it's a semantically different/new thing, like signup, then we should just add a new subcommand

**Comment by asim** [comment]
I personally feel like signup is a thing you do before login. We're compressing the two together but anywhere you go its "login or signup" and so it probably drastically simplifies things for us to have a built in OSS command thats purely `micro login` based on email/password stored by the auth service and signup as a service to exclusively signup to the platform. 

This also informs a longer term design decision where we potentially want to license micro/services as a commercial product for cloud providers. You could imagine they have existing users of micro OSS and they want to offer Micro as a Service and so when they do, all of a sudden signup and other commands appear as part of the login. Even more interestingly as you switch environments, those might be entirely different cloud providers which you signup for and login into.

**Pull request merged**
