### PR TITLE
Idea: `micro lint`

### PR DESCRIPTION
**Pull request by ben-toogood**

### CODE REVIEW

**Comment by asim** [comment]
Any sort of design/usage examples?

- looks for micro.mu
- looks for readme
- looks for proto dir

What the output might be like?

**Comment by ben-toogood** [comment]
> Any sort of design/usage examples?
> 
> * looks for micro.mu
> * looks for readme
> * looks for proto dir
> 
> What the output might be like?

For README.md / micro.mu we can just auto-generate these and output using logger.Info. For proto, i'm not sure since some users might not be using proto.

**Comment by asim** [comment]
Would be good to see it more fleshed out in this just to give more context to the reader

**Comment by ryano3000** [comment]
Needs Best practices documented somewhere, or this should be a source of truth for best practices. Examples could be - folder structure, linting of code around service initialization etc, would help as there are sometimes multiple ways to do things

**Comment by asim** [comment]
Needs more fleshing out before we can go anywhere with it but will merge so there's a starting point

**Pull request merged**
